# This is a basic workflow to help you get started with Actions

name: CI with Java and Gradle

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup Java
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with: 
          java-version: '11'
          distribution: 'adopt'
      - name: Checkout the code
        uses: actions/checkout@v2
    
      # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      # Run the build using gradle and upload build artefact
      - name: Build with gradle
        run: ./gradlew build
        uses: actions/upload-artifact@main
        with:
          name: gradle artefact
          path: build/libs

  # Test job
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download built artefact
        uses: actions/download-artifact@main
        with:
          name: gradle artefact
          path: build/libs

      # Setup Java
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Test the project with gradle
      - name: Test with Gradle
        run: ./gradlew test --info